#!/usr/bin/env ruby

begin
  require 'github_api'
  require 'highline/import'
  require 'rake'
  require 'netrc'
rescue LoadError
  puts "Missing Gems! Install with `gem install github_api highline rake netrc`"
  exit 1
end

RakeFileUtils.verbose_flag = false
include RakeFileUtils

netrc = Netrc.read
username, password = netrc["github.com"]

if username.nil?
  username = ask("Username: ")
  password = ask("Password: ") { |q| q.echo = false }
end

org = File.basename(Dir.pwd)

gh = Github.new(
  basic_auth: "#{username}:#{password}",
  auto_pagination: true,
)

sh("update-deps") if ENV['DEPS'] == '1'

repos = gh.repos.list(org: org).sort_by { |r| r[:name] }

repos.each do |repo|
  next if File.exist?(repo[:name])
  puts ">>> Cloning #{org}/#{repo[:name]}"
  sh("git clone #{repo[:clone_url]}")
end

sh("parallel --no-notice --verbose \"/bin/bash -c 'cd {} && update-git-repo'\" ::: #{repos.map { |x| x[:name] }.join(' ')}")
