source 'https://supermarket.zenops.net'

# role[base]
cookbook 'apt'
cookbook 'bash'
cookbook 'build-essential'
cookbook 'chef-client'
cookbook 'cron'
cookbook 'git'
cookbook 'gnupg'
cookbook 'hostmasters'
cookbook 'htop'
cookbook 'logrotate'
cookbook 'ssh'
cookbook 'tmux'
cookbook 'ubuntu'
cookbook 'vim'
