name 'mike'
maintainer 'Mike Szörnyi'
maintainer_email 'mike.szoernyi@gmail.com'
license 'Apache v2.0'
description 'My dotfiles'
long_description 'My dotfiles'
version '0.0.0'

depends 'bash'
depends 'vim'
